## Multinomial and Bernoulli Naive Bayes

For understanding Multinomial and Bernoulli Naive Bayes, we will start with a small example and understand the end to end process. In another notebook, we will build a full-fledged email spam classifier.

To start with, let's take a few sentences and classify them in two different classes - *education* or *cinema*. Each sentence will represent one document. In real-world cases, a document be any piece of text such as an email, a news article, a book review, a tweet etc.
The analysis and the algorithm involved doesn’t depend on the type of document we use.

The notebook is divided into the following sections:
1. Importing and preprocessing data
2. Building the model: Multinomial Naive Bayes
3. Building the model: Bernoulli Naive Bayes

### 1. Importing and Preprocessing Data

Let us first look at the sentences and their classes. We have kept the training sentences in file example_train.csv. Test sentences have been put in the file example_test.csv.

In [183]:
import numpy as np
import pandas as pd
import sklearn

# training data
train_docs = pd.read_csv('movie_review_train.csv') 
train_docs

class                                               text
0      Pos   a common complaint amongst film critics is   ...
1      Pos   whew   this film oozes energy   the kind of b...
2      Pos   steven spielberg s   amistad     which is bas...
3      Pos   he has spent his entire life in an awful litt...
4      Pos   being that it is a foreign language film with...
...    ...                                                ...
1595   Neg   if anything     stigmata   should be taken as...
1596   Neg   john boorman s   zardoz   is a goofy cinemati...
1597   Neg   the kids in the hall are an acquired taste   ...
1598   Neg   there was a time when john carpenter was a gr...
1599   Neg   two party guys bob their heads to haddaway s ...

[1600 rows x 2 columns]

So as you can see there are 5 documents (sentences) , 3 are of "education" class and 2 are of "cinema" class.

In [184]:
# convert label to a numerical variable
train_docs['class'] = train_docs['class'].map({'Neg':0, 'Pos':1})
train_docs

class                                               text
0         1   a common complaint amongst film critics is   ...
1         1   whew   this film oozes energy   the kind of b...
2         1   steven spielberg s   amistad     which is bas...
3         1   he has spent his entire life in an awful litt...
4         1   being that it is a foreign language film with...
...     ...                                                ...
1595      0   if anything     stigmata   should be taken as...
1596      0   john boorman s   zardoz   is a goofy cinemati...
1597      0   the kids in the hall are an acquired taste   ...
1598      0   there was a time when john carpenter was a gr...
1599      0   two party guys bob their heads to haddaway s ...

[1600 rows x 2 columns]

Let's now split the dataframe into X and y labels.

In [185]:
# convert the df to a numpy array 
train_array = train_docs.values

# split X and y
X_train = train_array[:,1]
y_train = train_array[:,0]
y_train = y_train.astype('int') # sklearn needs y as integers

# print("X_train")
# print(X_train)
# print("y_train")
# print(y_train)

### Creating the Bag of Words Representation

We now have to convert the data into a format which can be used for training the model. We'll use the **bag of words representation** for each sentence (document).

Imagine breaking X in individual words and putting them all in a bag. Then we pick all the unique words from the bag one by one and make a dictionary of unique words. 

This is called **vectorization of words**. We have the class ```CountVectorizer()``` in scikit learn to vectorize the words. 


In [186]:
# create an object of CountVectorizer() class 
from sklearn.feature_extraction.text import CountVectorizer 
# help(CountVectorizer)

In [187]:
vec = CountVectorizer()

Here ```vec``` is an object of class ```CountVectorizer()```. This has a method called  ```fit()``` which converts a corpus of documents to a matrix of 'tokens'.

In [188]:
# fit the vectorizer on training data 
vec.fit(X_train)
vec.vocabulary_

{'common': 6343,
 'complaint': 6419,
 'amongst': 1379,
 'film': 11923,
 'critics': 7439,
 'is': 16875,
 'why': 35407,
 'aren': 1839,
 'there': 32212,
 'more': 20840,
 'literate': 18743,
 'scripts': 28117,
 'available': 2351,
 'quiz': 25446,
 'show': 28864,
 'gives': 13369,
 'signs': 29019,
 'of': 22167,
 'hope': 15195,
 'that': 32168,
 'the': 32171,
 'art': 1958,
 'writing': 35819,
 'isn': 16903,
 'dead': 7967,
 'in': 15974,
 'hollywood': 15084,
 'and': 1457,
 'we': 35110,
 'need': 21440,
 'not': 21849,
 'only': 22295,
 'look': 18910,
 'to': 32570,
 'independent': 16117,
 'films': 11942,
 'for': 12399,
 'thoughtful': 32307,
 'content': 6831,
 'paul': 23237,
 'attanasio': 2205,
 'script': 28111,
 'takes': 31712,
 'what': 35283,
 'could': 7132,
 'have': 14515,
 'been': 2993,
 'tepid': 32066,
 'thriller': 32338,
 'scandals': 27828,
 'late': 18154,
 '50s': 313,
 'delivers': 8278,
 'telling': 31991,
 'parable': 23006,
 'about': 480,
 'emptiness': 10417,
 'post': 24373,
 'war': 34976,
 'amer

```Countvectorizer()``` has converted the documents into a set of unique words alphabetically sorted and indexed.


**Stop Words**

We can see a few trivial words such as  'and','is','of', etc. These words don't really make any difference in classyfying a document. These are called **stop words**. So we would like to get rid of them. 

We can remove them by passing a parameter stop_words='english' while instantiating ```Countvectorizer()``` as follows: 

In [189]:
# fitting the vectorizer on training data again
# removing the stop words this time
vec = CountVectorizer(stop_words='english',min_df=.03, max_df=.8)
vec.fit(X_train)
vec.vocabulary_

{'common': 264,
 'critics': 323,
 'aren': 78,
 'available': 101,
 'gives': 618,
 'hope': 693,
 'art': 81,
 'writing': 1632,
 'isn': 753,
 'dead': 342,
 'hollywood': 690,
 'need': 970,
 'look': 853,
 'films': 549,
 'content': 287,
 'paul': 1037,
 'script': 1248,
 'takes': 1429,
 'thriller': 1471,
 'late': 805,
 'delivers': 357,
 'telling': 1449,
 'post': 1089,
 'war': 1571,
 'american': 59,
 'dream': 413,
 'tv': 1512,
 'radio': 1145,
 'heavy': 673,
 'direction': 386,
 'robert': 1205,
 'performances': 1043,
 'john': 766,
 'rob': 1204,
 'perfectly': 1041,
 'usually': 1537,
 'quality': 1136,
 'sets': 1272,
 'camera': 192,
 'work': 1618,
 'recent': 1165,
 'century': 213,
 'period': 1044,
 'pieces': 1056,
 'years': 1638,
 'old': 1001,
 'images': 716,
 'true': 1502,
 'era': 464,
 'generation': 605,
 'gone': 625,
 '15': 4,
 'world': 1623,
 'themes': 1461,
 'good': 626,
 'life': 831,
 'family': 508,
 'match': 894,
 'father': 521,
 'fame': 506,
 'audience': 99,
 'appear': 72,
 'familiar': 507,
 

Notice that the vocabulary has reduced to 12 from 15. Another way of printing the 'vocabulary' is as follows:

In [190]:
# printing feature names
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['000' '10' '100' ... 'york' 'young' 'younger']
1643


So our final dictionary is made of 12 words (after discarding the stop words). Now, to do classification, we need to represent all the documents with these words (or tokens) as features. 

Every document will be converted into a *feature vector* representing presence of these words in that document. Let's convert each of our training documents in to a feature vector.

In [191]:
# another way of representing the features
X_transformed = vec.transform(X_train)
X_transformed

<1600x1643 sparse matrix of type '<class 'numpy.int64'>'
	with 217396 stored elements in Compressed Sparse Row format>

You can see X_tranformed is a 5 x 12 **sparse matrix**. It has 5 rows for each of our 5 documents and 12 columns each 
for one word of the dictionary which we just created. Let us print X_transformed.

In [192]:
print(X_transformed)

  (0, 4)	1
  (0, 59)	2
  (0, 72)	1
  (0, 78)	1
  (0, 81)	1
  (0, 99)	3
  (0, 101)	1
  (0, 192)	1
  (0, 211)	1
  (0, 213)	1
  (0, 220)	1
  (0, 264)	2
  (0, 287)	1
  (0, 316)	1
  (0, 323)	1
  (0, 328)	1
  (0, 340)	1
  (0, 342)	1
  (0, 357)	1
  (0, 386)	1
  (0, 413)	2
  (0, 445)	2
  (0, 464)	1
  (0, 503)	1
  (0, 506)	1
  :	:
  (1599, 1247)	1
  (1599, 1258)	2
  (1599, 1267)	1
  (1599, 1271)	1
  (1599, 1331)	1
  (1599, 1335)	1
  (1599, 1339)	1
  (1599, 1366)	3
  (1599, 1371)	1
  (1599, 1375)	1
  (1599, 1379)	1
  (1599, 1413)	1
  (1599, 1421)	1
  (1599, 1429)	2
  (1599, 1447)	1
  (1599, 1501)	1
  (1599, 1533)	1
  (1599, 1550)	1
  (1599, 1555)	1
  (1599, 1556)	1
  (1599, 1570)	1
  (1599, 1579)	2
  (1599, 1589)	1
  (1599, 1609)	1
  (1599, 1616)	1


This representation can be understood as follows:

Consider first 4 rows of the output: (0,2), (0,5), (0,7) and (0,11). It says that the first document (index 0) has 
7th , 2nd , 5th and 11th 'word' present in the document, and that they appear only
once in the document- indicated by the right hand column entry. 

Similarly, consider the entry (4,4) (third from bottom). It says that the fifth document has the fifth word present twice. Indeed, the 5th word('good') appears twice in the 5th document. 

In real problems, you often work with large documents and vocabularies, and each document contains only a few words in the vocabulary. So it would be a waste of space to store the vocabulary in a typical dataframe, since most entries would be zero. Also, matrix products, additions etc. are much faster with sparse matrices. That's why we use sparse matrices to store the data.


Let us convert this sparse matrix into a more easily interpretable array:

In [193]:
# converting transformed matrix back to an array
# note the high number of zeros
X_transformed.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

To make the dataset more readable, let us examine the vocabulary and the document-term matrix together in a pandas dataframe. The way to convert a matrix into a dataframe is ```pd.DataFrame(matrix, columns=columns)```.


In [194]:
# converting matrix to dataframe
pd.DataFrame(X_transformed.toarray(), 
             columns=vec.get_feature_names_out())

000  10  100  13  15  1995  1996  1997  1998  1999  ...  written  wrong  \
0       0   0    0   0   1     0     0     0     0     0  ...        0      0   
1       0   0    0   0   0     0     0     0     0     0  ...        0      0   
2       0   0    0   0   0     0     0     0     0     0  ...        0      1   
3       0   0    0   0   0     0     0     0     0     0  ...        0      0   
4       0   1    0   0   0     0     0     0     0     0  ...        0      0   
...   ...  ..  ...  ..  ..   ...   ...   ...   ...   ...  ...      ...    ...   
1595    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1596    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1597    0   0    0   0   0     0     0     0     0     0  ...        0      0   
1598    0   0    0   0   0     2     1     0     0     0  ...        1      1   
1599    0   0    0   0   0     0     0     0     0     0  ...        0      0   

      wrote  yeah  year  years  yes  york  young  younger  
0         0     0     0      3    0     0      0        0  
1         0     0     0      0    1     0      0        0  
2         0     0     1      0    0     0      0        0  
3         0     0     0      1    0     0      1        0  
4         0     0     0      0    0     0      0        0  
...     ...   ...   ...    ...  ...   ...    ...      ...  
1595      0     0     2      0    1     0      0        0  
1596      0     0     1      1    0     0      0        0  
1597      0     0     0      0    0     0      0        0  
1598      0     0     0      0    0     0      0        0  
1599      0     0     0      0    0     0      0        0  

[1600 rows x 1643 columns]

This table shows how many times a particular word occurs in document. In other words, this is a frequency table of the words.

A corpus of documents can thus be represented by a matrix with one row per document and one column per
token (e.g. word) occurring in the corpus.

Let's now import and transform the test data as well.

In [195]:
# test data
test_docs = pd.read_csv('movie_review_test.csv') 
test_docs

class                                               text
0     Pos   films adapted from comic books have had plent...
1     Pos   every now and then a movie comes along from a...
2     Pos   you ve got mail works alot better than it des...
3     Pos      jaws   is a rare film that grabs your atte...
4     Pos   moviemaking is a lot like being the general m...
..    ...                                                ...
395   Neg   one of the first films of 1999 is this mtv pi...
396   Neg   susan granger s review of   america s sweethe...
397   Neg   susan granger s review of   jeepers creepers ...
398   Neg   this independent film written and directed by...
399   Neg   come on hollywood   surprise me    stop givin...

[400 rows x 2 columns]

In [196]:
# convert label to a numerical variable
test_docs['class'] = test_docs['class'].map({'Neg':0, 'Pos':1})
test_docs

class                                               text
0        1   films adapted from comic books have had plent...
1        1   every now and then a movie comes along from a...
2        1   you ve got mail works alot better than it des...
3        1      jaws   is a rare film that grabs your atte...
4        1   moviemaking is a lot like being the general m...
..     ...                                                ...
395      0   one of the first films of 1999 is this mtv pi...
396      0   susan granger s review of   america s sweethe...
397      0   susan granger s review of   jeepers creepers ...
398      0   this independent film written and directed by...
399      0   come on hollywood   surprise me    stop givin...

[400 rows x 2 columns]

In [197]:
# convert to numpy array
test_numpy_array = test_docs.values

# split into X and y
X_test = test_numpy_array[:,1]
y_test = test_numpy_array[:,0]
y_test = y_test.astype('int')

# print("X_test")
# print(X_test)
# print("y_test")
# print(y_test)
print(len(y_test))

400


In [198]:
# transform the test data
# note that you *never* fit on test data, only on training data
# and only transform the test data
X_test_transformed = vec.transform(X_test)
X_test_transformed

<400x1643 sparse matrix of type '<class 'numpy.int64'>'
	with 51663 stored elements in Compressed Sparse Row format>

In [199]:
# convert to non-sparse array
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 2, 0]])

Let us summarise all we have done till now:

- ```vect.fit(train)``` learns the vocabulary of the training data
- ```vect.transform(train)``` uses the fitted vocabulary to build a document-term matrix from the training data
- ```vect.transform(test)``` uses the fitted vocabulary to build a document-term matrix from the testing data (and ignores tokens it hasn't seen before)

### 2. Building the Model: Multinomial Naive Bayes

In [200]:
# building a multinomial NB model
from sklearn.naive_bayes import MultinomialNB

# instantiate NB class
mnb=MultinomialNB()

# fitting the model on training data
mnb.fit(X_transformed, y_train)

# note that we are using the sparse matrix X_transformed, 
# though you can also use the non-sparse version
# mnb.fit(X_transformed.toarray(), y_train) 

# predicting probabilities of test data
proba = mnb.predict_proba(X_transformed)

# predict class
y_pred_class = mnb.predict(X_transformed)


In [218]:
y_pred_class

array([1, 1, 1, ..., 0, 0, 0])

In [201]:
# probability of each class (test data)
print("probability of test document belonging to class NEG" , proba[:,0])
print("probability of test document belonging to class POS" , proba[:,1])

probability of test document belonging to class NEG [5.23399325e-07 2.72421341e-01 7.31524536e-10 ... 9.99978776e-01
 9.99987658e-01 9.99998171e-01]
probability of test document belonging to class POS [9.99999477e-01 7.27578659e-01 9.99999999e-01 ... 2.12235096e-05
 1.23421213e-05 1.82856815e-06]


In [207]:
from sklearn import metrics
metrics.accuracy_score(y_train, y_pred_class)

0.865625

In [232]:

# note that we are using the sparse matrix X_transformed, 
# though you can also use the non-sparse version
# mnb.fit(X_transformed.toarray(), y_train) 

# predicting probabilities of test data
proba = mnb.predict_proba(X_test_transformed)

# predict class
y_test_pred_class = mnb.predict(X_test_transformed)

In [233]:
metrics.accuracy_score(y_test, y_test_pred_class)

0.8275

In [217]:
# confusion matrix
metrics.confusion_matrix(y_test, y_test_pred_class)
# help(metrics.confusion_matrix)

array([[172,  28],
       [ 41, 159]])

### 3. Building the Model: Bernoulli Naive Bayes

In [239]:
from sklearn.naive_bayes import BernoulliNB

# instantiating bernoulli NB class
bnb=BernoulliNB()

# fitting the model
bnb.fit(X_transformed, y_train)

# also works
# bnb.fit(X_transformed.toarray(), y_train)

# predicting probability of test data
y_bnb_test_pred = bnb.predict(X_test_transformed)
prob_bnb = bnb.predict_proba(X_test_transformed)
prob_bnb

array([[9.48171309e-03, 9.90518287e-01],
       [6.49769619e-03, 9.93502304e-01],
       [3.94902967e-01, 6.05097033e-01],
       [2.04992401e-12, 1.00000000e+00],
       [9.98827241e-01, 1.17275875e-03],
       [1.78941734e-12, 1.00000000e+00],
       [5.94773559e-07, 9.99999405e-01],
       [2.02838492e-03, 9.97971615e-01],
       [9.17950086e-01, 8.20499136e-02],
       [9.44944057e-02, 9.05505594e-01],
       [9.97389573e-04, 9.99002610e-01],
       [8.55906408e-04, 9.99144094e-01],
       [3.30288186e-03, 9.96697118e-01],
       [2.50950625e-02, 9.74904938e-01],
       [7.32820406e-05, 9.99926718e-01],
       [5.14487298e-01, 4.85512702e-01],
       [9.77854644e-01, 2.21453565e-02],
       [2.42691437e-09, 9.99999998e-01],
       [9.44024181e-03, 9.90559758e-01],
       [9.91992498e-01, 8.00750156e-03],
       [9.66449102e-01, 3.35508975e-02],
       [4.86743623e-03, 9.95132564e-01],
       [9.99484407e-01, 5.15592846e-04],
       [2.34114640e-08, 9.99999977e-01],
       [1.307296

In the next notebook, we will use Multinomial and Bernoulli Naive Bayes to solve an interesting real problem - classifying SMSes as spam or ham. We'll also see how to decide the optimal cutoff probability and evaluate the model.


In [240]:
metrics.accuracy_score(y_test, y_bnb_test_pred)


0.79

In [241]:
type(y_test)

numpy.ndarray

In [242]:
metrics.confusion_matrix(y_test, y_bnb_test_pred)


array([[177,  23],
       [ 61, 139]])

In [243]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [244]:
y_bnb_test_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,